INSERT INTO USERS (USERID, USERNAME, SALT, PASSWORD,  FIRSTNAME, LASTNAME) SELECT * FROM  ( SELECT 1, 'admin', 'E98+Mu14+VqHr4DqMNwzrg==', 'ftP4R4mVSd08JJhBRAVRyg==',
'SYSTEM', 'ADMIN') AS tmp
where not exists (select USERID from USERS WHERE USERID = 1) LIMIT 1;

